name: build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  #: Run the test every week
  schedule:
    - cron: "0 12 * * 1"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies [Svelte]
      run: cd svelte-ts && npm install
    - name: Build [Svelte]
      run: npm run build && npm run build:notebook && cd ..
    - name: Install dependencies [Vanilla]
      run: cd vanilla-ts && npm install
    - name: Build [Vanilla]
      run: npm run build && npm run build:notebook && cd ..
    - name: Install dependencies [React]
      run: cd react-js && npm install
    - name: Build [React]
      run: npm run start && npm run build